name: brain_note
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  google_sign_in: ^7.2.0
  google_sign_in: ^6.2.1
  flutter_riverpod: ^3.2.1
  http: ^1.6.0
  shared_preferences: ^2.5.4
  routemaster: ^1.0.1
  flutter_quill: ^11.5.0
  socket_io_client: ^3.1.4
  firebase_auth: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/images/docs-logo.png
   - assets/images/g-logo-2.png

